language: node_js
node_js:
  - "6"
before_script:
  - "npm install"
  - "sudo apt-get update"
  - "sudo apt-get install graphicsmagick"
  - chmod 755 ./travis/push.sh
script:
  - "gulp build"
after_success:
  - ./travis/push.sh
