language: node_js
node_js:
  - "6"
before_script:
  - "npm install"
  - "sudo apt-get update"
  - "sudo apt-get install graphicsmagick"
script:
  - "gulp images"
  - "gulp build"
after_success:
  - .travis/push.sh
env:
  global:
    secure: KXJiAtzP47OULc/jUMxisNLrxIyjEVslb3ZJtYyXWGKKHsVjO/zDOkhGt4tmSVk1yZ7w2vJFXd0u7bbcA5UzQZ78A04j061ID2Mnd854RzMRxx4y7DqEkUpYjogk/SjmEV0OD+nuCiLj7CB/tSOL5VbNQcoC6nP8DmdGiIb2yIu8/zyrY/AvCZUVpPKWnL/TehArSU+tZrzc0PKe9GvIc6u3quvFsnnp1Y5nxMfbTeaQbzlz65AVGiyirU8a6JPavNgPk42itc93xv65vma27jRNcH8JW85EweJuP+yjIwNt5L8O/HQ4MeLZFhYwGViz6RgfCGOFlOIdMHv78hSWuxBF8QKHv6eKWANsFPZ9zWuL+oxgC2HB+6dfXqBmY1/UHhhrKEY3TfAJyoHIYviSreSXUyrXo8UCTrN68vGTV5fFxRFeaB6CgNRxZAyKa3TCEgnSgqpAQKPZO7QfVRJYkrrfeeRQgN0UuPYp9/WbHBKDKcCacWS+DapUZ+fPJr46oLVJj4//7wju/lFOz0r5ZSJRyvCrW40233vlZdGMi6GOc89+v+f4TsTL4pOjSnbnKptJP7M3PPvcLEEsiX6S/e6aL+u+4GYlkVdJbihSDPrE3X2r61COus+5tBDE651cIZ3ls0NuzV/0k1bej5PEDf+XJFQ5r4l/ugMb2lDUvlU=
