language: node_js
node_js:
  - "6"
before_script:
  - "npm install"
  - "sudo apt-get update"
  - "sudo apt-get install graphicsmagick"
script:
  - "gulp images"
  - "gulp build"
after_success:
  - ./travis/push.sh
